#version: "3.9"
#services:
#
#  db:
#    image: postgres:latest
#    container_name: postgres_db
#    ports:
#      - "5431:5432"
#    environment:
#      POSTGRES_USER: 'postgres'
#      POSTGRES_PASSWORD: 'postgres'
#      POSTGRES_DB: 'diplom'



#version: "3.9"
#services:
#
#  db:
#    image: postgres:14.3-alpine3.15
#    ports:
#      - "5431:5432"
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}

version: "3.9"
services:

  postgres:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

#services:
#  postgres-db:
#    image: postgres:latest
#    container_name: postgres_db
#    environment:
#      - .env
#    ports:
#      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

#  backend:
#    build:
#      context: /home/vit/Desktop/netology/python-final-diplom/reference/netology_pd_diplom/backend
#      dockerfile: /home/vit/Desktop/netology/python-final-diplom/reference/netology_pd_diplom/Dockerfile
#    container_name: backend
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_HOST: ${DB_HOST}
#      POSTGRES_PORT: ${DB_PORT}

